### ISSUE TITLE
On Medium-of-Exchange Token Valuations

### ISSUE THREAD

**Issue by XiaohuaNpc** [npc-network/translator-website#6]
https://vitalik.ca/general/2017/10/17/moe.html

**Comment by su8su** [comment]
认领

**Comment by callmewhy** [comment]
文章地址：source/_drafts/on-medium-of-exchange-token-valuations.md
感谢～

**Comment by callmewhy** [comment]
辛苦啦，长文已发布～
https://t.npc.network/2018/07/10/on-medium-of-exchange-token-valuations/

有些细节需要优化，我周末修正一下，稍后会同步到我们的公众号上

**Comment by callmewhy** [comment]
添加了一下文末的译者信息，不好意思给漏了。
然后文章的一些语句也做了调整，现在更新了：/_drafts/why-you-probably-shouldnt-use-a-single-private-key-to-secure-your-assets.md
