### ISSUE TITLE
GAVIN ANDRESEN: Not as rich as you think

### ISSUE THREAD

**Issue by XiaohuaNpc** [npc-network/translator-website#8]
http://gavinandresen.ninja/not-as-many-as-you-think

**Comment by proofofbuild** [comment]
认领

**Comment by callmewhy** [comment]
草稿在 /source/_drafts 里，参考我们的协作流程找到对应的草稿翻译即可。翻译愉快～

**Comment by callmewhy** [comment]
感觉翻译的有些生硬，很多地方英文翻译成中文的时候丢失了一些细节，不够连贯。我做了一些修改。

已经发布，感谢 @blakegao ～

https://t.npc.network/2018/07/05/not-as-many-as-you-think/
